### ISSUE TITLE
country code -> name conversion is extremely slow

### ISSUE THREAD

**Issue by how-to-do-frontend** [HorizonCode/bpy-web#1]
i'd recommend using [country-list](https://www.npmjs.com/package/country-list) as it's a lot faster (tested both with bpy-web, country-list was noticeably faster)

**Comment by HorizonCode** [comment]
resolved with [970477d](https://github.com/HorizonCode/bpy-web/commit/970477db70dc95f15f5c4cebbd07ae1b8451c99a)
