### ISSUE TITLE
Country flag vanishes if the screen width is too small

### ISSUE THREAD

**Issue by marcandreher** [HorizonCode/bpy-web#3]
**Reproduction:**
![Digga](https://github.com/HorizonCode/bpy-web/assets/35847627/6b2e5547-1c36-44f5-a93c-09a4cb0419b7)

**Comment by HorizonCode** [comment]
fixed with commit https://github.com/HorizonCode/bpy-web/commit/1b88c9afacdccf6b63e8aec8d2275950a9f2771c
