### ISSUE TITLE
Tooltips don't leave the inner container

### ISSUE THREAD

**Issue by marcandreher** [HorizonCode/bpy-web#4]
**Reproduction:**
![WTF](https://github.com/HorizonCode/bpy-web/assets/35847627/86a50c72-bdb3-4ecf-af6e-2efd7cf5abe6)

**Comment by HorizonCode** [comment]
fixed with commit https://github.com/HorizonCode/bpy-web/commit/770605e262487e062697314290cadad10472ac75
