### ISSUE TITLE
Frontend's navigation get's stuck in beatmap page

### ISSUE THREAD

**Issue by marcandreher** [HorizonCode/bpy-web#5]
**Reproduction:**
![Stuck](https://github.com/HorizonCode/bpy-web/assets/35847627/ae987940-7d3b-42b8-ba66-1bd50c8b67ee)

**Comment by HorizonCode** [comment]
This Issue is because the PR for the country field is still pending and not merged into the main branch of bancho.py

https://github.com/osuAkatsuki/bancho.py/pull/649
