### ISSUE TITLE
TD Mod in Beatmap view is padding Scores table

### ISSUE THREAD

**Issue by marcandreher** [HorizonCode/bpy-web#6]
![image](https://github.com/HorizonCode/bpy-web/assets/35847627/611b6324-9e72-49cd-8842-38042bf44162)
on Beatmap page

**Comment by HorizonCode** [comment]
fixed with [#b350711](https://github.com/HorizonCode/bpy-web/commit/b350711fe0768d3099e777e41fed1bf1c7c9b2f5)
